# Generated by Django 5.1.5 on 2025-04-11 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('estimated_delivery_time', models.CharField(max_length=255)),
                ('image_url', models.URLField(max_length=1024)),
            ],
        ),
    ]
