# Generated by Django 5.1.5 on 2025-03-19 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='extra_shots',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='drink',
            name='milk_options',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='drink',
            name='sizes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='drink',
            name='syrup_options',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='customizations',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
