# Generated by Django 5.1.5 on 2025-04-13 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_drink_extra_shots_drink_milk_options_drink_sizes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='used_free_drink',
            field=models.BooleanField(default=False),
        ),
    ]
